const getRandom = require('lib/arr').random
const greetings = [
 'Hello',
 'Hello There',
 'Well Hello There',
 'Greetings',
 'Wesh, b1 ou b1 ???',
 'Learning C is character building',
 'Shalom',
 'Word',
 'Sup.',
 'Hihi',
 'What is crack a lacking?',
 'Howyadoin\'?',
 'Dudester!',
 'Alrighty then!',
 'Hola',
 'Guten Tag',
 'Oh Hiii',
 'Oh hi there',
 'Howdy',
 'Bonjour',
 'Speak!',
 'Hey',
 'Hey There',
 'Moshi moshi',
 'Yo',
 'Domino\'s Pizza, pickup or delivery?',
 'What\'s up?',
 'sup\' ?',
 'What\'s up bitches?',
 'Good day to you!',
 'A Hoy Hoy!',
]

module.exports = () => getRandom(greetings)
